# Generated by Django 6.0.5 on 2026-05-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job_posted_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="created_at",
            new_name="applied_at",
        ),
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("shortlisted", "Shortlisted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
