# Generated by Django 6.0.5 on 2026-05-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("candidate", "Candidate"), ("recruiter", "Recruiter")],
                default="candidate",
                max_length=20,
            ),
        ),
    ]
